### PR TITLE
Fix django cache key cleanup, closes #32

### LINKED ISSUE #32: Session keys not mangled in performance files
Session keys in django are generated by taking 32 random chars in `string.ascii_lowercase + string.digits` (see [django.contrib.sessions.backends.base](https://github.com/django/django/blob/stable/1.10.x/django/contrib/sessions/backends/base.py#L163)), however this pattern is not mangled by regexes in `django_perf_rec.cache.CacheOps.VARIABLE_RES̀`.

Should we add `/\b[0-9a-z]{32}\b/` to the list ? That seems acceptable to me as 32-letter column/table/variable without underscores or uppercase letters should not be very frequent.

### PR DESCRIPTION
**Pull request by njoyard**

### CODE REVIEW

**Comment by njoyard** [comment]
Actually no, don't merge that. It won't work well. Cache keys are prefixed, I'll reopen a new PR.

**Comment by adamchainz** [comment]
No this is fine, the regex matches things *inside* the key, not the whole key

**Comment by njoyard** [comment]
Yeah but cache keys like `django.contrib.sessions.cacheabcdefghijklmnopqrstuvwxyz01zz45` will be mangled to `django.contrib.sessions.#zz#`, which will keep a variable part...

**Comment by njoyard** [comment]
Rewrote the fix, should be fine now.

**Comment by adamchainz** [comment]
Oh I see, I thought you mean the cache backend prefix, not the session backend's extra prefix. It is odd that there isn't even a separator of some kind between session backend key prefix, it's probably just an oversight.

**Comment by adamchainz** [comment]
Merged in 541f5a3cad04b7aa127e39c4f5053a70b3a0f26c, thanks! I added an improvement in 0ead0d068776f3ece2457007f6709310766395fc to use regex lookbehind to check for the prefixes, so we can leave the it in the 'fingerprinted' version so it's easier to understand from the `.perf.yml` file where the cache operations are coming from 😄

**Pull request closed without merging**
